import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import { House } from 'lucide-react';
import "./globals.css";

import Sidebar from '../components/Sidebar/Sidebar';

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en">
      <body className={`${robotoMono.variable} antialiased flex min-h-screen`}>
        <Sidebar />
        <main className={'flex-1 flex justify-center items-center'}>{children}</main>
      </body>
    </html>
  );
}
