'use client';

import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import { useState, useEffect } from "react";
import { House } from 'lucide-react';
import "./globals.css";

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["700"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  const [activeSection, setActiveSection] = useState('home');

  // Функція для плавного скролу при кліку
  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };



  // Компонент однієї кнопки меню (щоб не дублювати код)
  const NavItem = ({ id, label, icon: Icon }: any) => {
    const isActive = activeSection === id;

    return (
      <li
        onClick={() => scrollToSection(id)}
        className={`
          flex justify-start items-center cursor-pointer h-16 transition-colors duration-300 
          ${isActive ? 'bg-gray-200 text-black border-l-8 border-l-black border-r-8 border-r-white' : 'hover:bg-gray-800 hover:text-white'}
        `}
      >
        <div className="w-[calc(100vw/24)] flex justify-center items-center">
          <Icon className="w-3/5 h-auto" />
        </div>
        <p className="opacity-0 group-hover:opacity-100 transition-opacity duration-300 ml-4">
          {label}
        </p>
      </li>
    );
  };

  return (
    <html lang="en">
      <body className={`${robotoMono.variable} antialiased flex min-h-screen`}>
        <nav className={`fixed group w-1/24 flex flex-col items-start hover:w-[300px] min-h-screen border-white
                          overflow-hidden whitespace-nowrap
                          transition-all duration-500 ease-in-out
                          bg-white
                          `}>
          <ul className={'flex-1 flex flex-col justify-center gap-4 font-bold text-[1vw] w-[300px]'}>
            <NavItem id="home" label="Home" icon={House} />
            <NavItem id="about" label="About" icon={House} />
            <NavItem id="contact" label="Contact" icon={House} />
          </ul>
        </nav>
        <main className={'flex-1 flex justify-center items-center'}>{children}</main>
      </body>
    </html>
  );
}
